archs = {
    "ogbn_withLabel": [['PF', 'PAPP', 'PFPF', 'PPPF', 'PAIAP', 'PAPFP', 'PFPPP', 'PPAPF', 'PAIAPF', 'PAIAPP', 'PAPAPF', 'PAPPPF', 'PFPPAP', 'PFPPPF', 'PPAPPF', 'PAIAPAP', 'PAPAPPP', 'PAPPPAP', 'PFPPPPP', 'PPAPPPF', 'PPPAPAP', 'PPPAPPF', 'PPPPAPF'], ['PP', 'PAP', 'PPAP', 'PPPP', 'PAIAP', 'PFPAP', 'PPAPP']],
    "ogbn_withoutLabel": [['PF', 'PAPF', 'PFPP', 'PAPPP', 'PFPFP', 'PPAPP', 'PPPAP', 'PPPFP', 'PAIAPP', 'PAPAPF', 'PFPAPF', 'PFPPPF', 'PFPPPP', 'PPAPPF', 'PPPAPF', 'PPPPAP', 'PPPPPF', 'PAIAPAP', 'PAPAPAP', 'PAPAPPP', 'PAPPPAI', 'PAPPPPF', 'PAPPPPP', 'PFPAPAP', 'PFPPFPF', 'PFPPPPF', 'PPAPAPF', 'PPAPAPP', 'PPPAIAI', 'PPPAPPP'], []],
    }
